
version = "2.10"

doCheck = true

[src]
url = "mirror://gnu/hello/hello-2.10.tar.gz"
sha256 = "0ssi1wpaf7plaswqqjwigppsg5fyh99vdlb9kzl7c9lng89ndq1i"

[meta]
description = "A program that produces a familiar, friendly greeting"
longDescription = """
GNU Hello is a program that prints "Hello, world!" when you run it.
It is fully customizable.
"""
homepage = "https://www.gnu.org/software/hello/manual/"
changelog = "https://git.savannah.gnu.org/cgit/hello.git/plain/NEWS?h=v2.10"
# license = "gpl3Plus"
# maintainers = [ "eelco" ]
# platforms = "all"
